server.port=8081
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_retours
spring.datasource.username=postgres
spring.datasource.password=0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt.secret=7dff7c4273822b314959db62f83196f7c4273822b314959db62f83196f7c4273822b314959db62f83196f
jwt.expiration=86400000
